services:
  api-server:
    build:
      context: ./BE
      dockerfile: Dockerfile.api
    container_name: api
    env_file:
      - .env
    networks:
      - my-network

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    container_name: nginx
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - my-network

  redis:
    image: redis:7.4.1-alpine
    container_name: redis
    networks:
      - my-network

  socket-server:
    build:
      context: ./BE
      dockerfile: Dockerfile.socket
    container_name: socket
    env_file:
      - .env
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
