FROM node:22-alpine AS build
WORKDIR /app

COPY ./api-server/package*.json ./
RUN npm install 

COPY ./api-server ./
RUN npm run build


FROM node:22-alpine AS production
WORKDIR /app

COPY ./api-server/package*.json ./
RUN npm install --only=production
COPY --from=build /app/dist ./dist

EXPOSE 3000

CMD ["node", "dist/main.js"]