# 빌드
FROM node:22-alpine AS build
WORKDIR /app

COPY ./client/package*.json ./
RUN npm install

COPY ./client ./

RUN npm run build

# 웹서버
FROM nginx:alpine

WORKDIR /

COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/dist ./var/www/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]