services:
  api-server:
    build:
      context: .
      dockerfile: Dockerfile.api-server
    container_name: api-server
    env_file:
      - .env
    networks:
      - my-network

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    container_name: nginx
    volumes:
      - ./ete/letsencrypt:/etc/letsencrypt:ro
    networks:
      - my-network

  redis:
    image: redis:7.4.1-alpine
    container_name: redis-container
    networks:
      - my-network

  socket-server:
    build:
      context: .
      dockerfile: Dockerfile.socket-server
    container_name: socket-server
    env_file:
      - .env
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
