# 빌드
FROM node:22-alpine AS build
WORKDIR /app

COPY ./client/package*.json ./

RUN apk update && apk add build-base g++ cairo-dev pango-dev giflib-dev
RUN npm install

COPY ./client ./

EXPOSE 5173

CMD ["npm", "run", "dev"]

