FROM node:22-alpine
WORKDIR /app

RUN npm install -g @nestjs/cli

COPY package*.json ./
COPY nest-cli.json ./
COPY tsconfig*.json ./

COPY apps/api-server/package*.json ./apps/api-server/
COPY libs ./libs

RUN npm install

EXPOSE 3000
